Bridge UI demo
Snowfork/substrate-ui pull request #12
Opened 2020-09-16 12:51 UTC by denalimarsh

A Bridge UI that enables the transfer of ETH and ERC20 tokens from Ethereum to Substrate via Metamask. The readme has steps for deployment and testing.

After entering a valid ERC20 token's contract address the user is able to approve, then send tokens to the ERC20App smart contract. Allowances/balances are fetched on the first load, then every 10 seconds.

## Initial load
<img width="977" alt="Screen Shot 2020-09-16 at 1 47 02 PM" src="https://user-images.githubusercontent.com/15370712/93339101-7812c680-f82b-11ea-9440-0f1d80aec778.png">

## ETHApp
<img width="956" alt="Screen Shot 2020-09-16 at 1 46 29 PM" src="https://user-images.githubusercontent.com/15370712/93339332-bc05cb80-f82b-11ea-8d0a-e2cb101bf2b9.png">

## ERC20App
<img width="948" alt="Screen Shot 2020-09-16 at 1 43 34 PM" src="https://user-images.githubusercontent.com/15370712/93339238-9d9fd000-f82b-11ea-82fd-8d0131f8197c.png">

## Sidebar
<img width="174" alt="Screen Shot 2020-09-16 at 2 37 34 PM" src="https://user-images.githubusercontent.com/15370712/93339135-82cd5b80-f82b-11ea-9c07-1f61bf453088.png">

2020-09-16 15:28 UTC, philipstanislaus approved these changes
LGTM!

2020-09-16 15:28 UTC, philipstanislaus commented on packages/app-polkadot-ethereum-bridge/src/config.tsx
> +export const APP_ERC20_CONTRACT_ADDRESS : string = "0xab6C826447Ec52bD7Fd1aaa19f420eDb7A302c8F";
Seems we have no linter in this repository – could you add that?

2020-09-16 15:28 UTC, philipstanislaus commented on packages/app-polkadot-ethereum-bridge/README.md
> +rm ./yarn.lock
Why is that needed?

2020-09-16 15:34 UTC, vgeddes requested changes
Looks good! One problem though is that it doesn't build: https://github.com/Snowfork/substrate-ui/pull/12/checks?check_run_id=1123164163

You can fix the Json import errors by following this guide: https://mariusschulz.com/articles/importing-json-modules-in-typescript

I wouldn't know how to fix the other build errors. As an experiment, maybe try basing your work off `master` instead of stable-base?

2020-09-16 16:03 UTC, vgeddes commented
Does this PR obsolete #8? I see it is still unmerged.

2020-09-16 22:05 UTC, vgeddes commented on packages/app-polkadot-ethereum-bridge/src/config.tsx
> +export const APP_ERC20_CONTRACT_ADDRESS : string = "0xab6C826447Ec52bD7Fd1aaa19f420eDb7A302c8F";
Turns out there is a linter, but the job was aborted for some reason: https://github.com/Snowfork/substrate-ui/pull/12/checks?check_run_id=1123164092

But yeah, I'm seeing lots of lint errors while I've got the code checked out locally.

2020-09-16 23:10 UTC, denalimarsh commented on packages/app-polkadot-ethereum-bridge/README.md
> +rm ./yarn.lock
I repeatedly hit an error while installing deps and found this to be a workable solution. Didn't dig into it too far, so not sure if it's due to legacy issues with the codebase or my configuration. @vgeddes maybe you've already addressed this locally while working with the build process?

2020-09-16 23:14 UTC, denalimarsh commented
> Does this PR obsolete #8? I see it is still unmerged.

Yeah, it does. Those changes are included in this PR. Closed it 👍

2020-09-17 01:16 UTC, vgeddes commented on packages/app-polkadot-ethereum-bridge/README.md
> +rm ./yarn.lock
I've made the app compatible with the `master` branch in https://github.com/Snowfork/substrate-ui/pull/14. Didn't run into any issues there.

2020-09-17 01:18 UTC, vgeddes commented
@denalimarsh lets consider closing this PR in favour of https://github.com/Snowfork/substrate-ui/pull/14. Didn't run into any issues there. I've made it compatible with the `master` branch and it builds cleanly.

2020-09-17 07:22 UTC, denalimarsh commented
Closing in favor of https://github.com/Snowfork/substrate-ui/pull/14.

2020-09-17 07:22 UTC, closed without merging