Update UI to M4 contracts
Snowfork/substrate-ui pull request #8
Opened 2020-09-08 19:15 UTC by denalimarsh

This PR updates the substrate-ui hosted Ethereum-Metamask app to M4. At the end of M5 additional changes will be required (integrate broker contract, use Ropsten network, refactor to allow for dynamic token contract addresses).

- Components are now based on applications (AppEthereum, AppERC20)
- Contract instance initialization in Bridge.tsx
- Add config.tsx
- Update contract ABIs to M4 state

2020-09-09 10:00 UTC, vgeddes requested changes
Looks good! Added a few minor review comments about naming.

2020-09-09 10:00 UTC, vgeddes commented on packages/app-polkadot-ethereum-bridge/src/AppEthereum.tsx
> +            Ethereum App
Could we rather refer to the "Ethereum App" as the "ETH App"? We should try to be consistent about our naming across all our components. For example, on the substrate side we have a ERC20 and an ETH app.

I think that "ETH" is technically more correct than "Ethereum", since the app focuses only on ETH, the native currency of the Ethereum system.

2020-09-09 10:00 UTC, vgeddes commented on packages/app-polkadot-ethereum-bridge/src/Bridge.tsx
> +import AppEthereum from "./AppEthereum";
As per my previous comment about naming we should consider having this instead:
```suggestion
import AppETH from "./AppETH";
```

2020-09-09 10:00 UTC, vgeddes commented on packages/app-polkadot-ethereum-bridge/src/Bridge.tsx
> +import * as EthereumApp from "./contracts/EthereumApp.json";
As per my previous comment about naming we should consider having this instead:
```suggestion
import * as ETHApp from "./contracts/ETHApp.json";
```

2020-09-09 10:45 UTC, denalimarsh commented on packages/app-polkadot-ethereum-bridge/src/AppEthereum.tsx
> +            Ethereum App
Yea I was thinking the same thing. Are we comfortable renaming the contract from 'EthereumApp' to 'AppETH' in M5 and then updating the substrate-ui naming conventions based on that in a future PR?

2020-09-15 22:40 UTC, vgeddes commented on packages/app-polkadot-ethereum-bridge/src/AppEthereum.tsx
> +            Ethereum App
sorry, I forgot to reply earlier. Sounds fine with me.

2020-09-16 23:14 UTC, closed without merging